### ISSUE TITLE
error when <g8 scalatra/scalatra-sbt>

### ISSUE THREAD

**Issue by clevertension** [scalatra/scalatra-sbt.g8#51]
java.lang.NoClassDefFoundError: scopt/OptionParser
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at xsbt.boot.Launch$$anon$5.entryPoint$lzycompute(Launch.scala:306)
    at xsbt.boot.Launch$$anon$5.entryPoint(Launch.scala:304)
    at xsbt.boot.Launch$$anon$5.newMain(Launch.scala:316)
    at xsbt.boot.Launch$.run(Launch.scala:108)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: scopt.OptionParser
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

**Comment by takezoe** [comment]
Try to use `sbt new` instead of `g8`.
